title: "Deploy a .NET application to Microsoft Windows instances"
description: "Deploy a sample ASP .NET application in a highly available configuration, with two Windows instances and a load balancer."
schemaVersion: 1.1.0
version: "20190304"
locale: "en"

variableGroups:
- title: General Configuration
  visible: false
  variables:
  - tenancy_ocid
  - region
  - compartment_ocid
  

- title: Windows Remote Desktop Configuration
  visible: true  
  variables:
    - instance_password

- title: Advanced Configuration
  visible: false  
  variables:
    - num_nodes
    - instance_ocpus
    - load_balancer_shape_details_maximum_bandwidth_in_mbps
    - load_balancer_shape_details_minimum_bandwidth_in_mbps
    - subnet_cidr
    - instance_shape
    - instance_name
    - availability_domain
    - userdata
    - cloudinit_ps1
    - cloudinit_config
    - index_html
    - image_os
    - image_os_version
    - is_winrm_configured_for_image
    - is_winrm_configured_for_ssl


outputGroups:
- title: Deployment Details
  outputs:
    - instance_public_ip1
    - instance_public_ip2
    - username1
    - username2
    - lb_public_ip

outputs:
  instance_public_ip1:
    type: link
    title: Instance 1
    description: Public IP for connecting to instance 1 over Remote Desktop
  instance_public_ip2:
    type: link
    title: Instance 2 Public IP
    description: Public IP for connecting to instance 2 over Remote Desktop
  username1:
    type: link
    title: Username (instance 1)
    description: User name login to instance 1
  username2:
    type: link
    title: Username (instance 2)
    description: Username to login to instance 2
  lb_public_ip:
    type: link
    title: Launch Application
    description: Open the ASP.NET application deployed to OCI

primaryOutputButton: lb_public_ip

variables:
  instance_password:
    type: password
    required: true
    title: "Windows login password for user: opc"
    description: "Used to login to the instance over remote desktop. Password must at least 12 characters long and include at least one uppercase letter, one lowercase letter, and one numeric character"
    pattern: "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?]).{12,32}$"
    visible: true
  compartment_ocid:
    type: oci:identity:compartment:id
    title: "Compartment"
    description: "The compartment in which to create Apex instance"
    required: true
  load_balancer_shape_details_maximum_bandwidth_in_mbps:
    type: string
    required: false
    visible: false
    title: "Load Balancer Max Bandwidth"
    description: "Maximum Bandwidth the Load Balancer will scale to"
  load_balancer_shape_details_minimum_bandwidth_in_mbps:
    type: string
    required: false
    visible: false
    title: "Load Balancer Min Bandwidth"
    description: "Minimum Bandwidth the Load Balancer will scale to"
  instance_shape:
    type: string
    required: false
    visible: false
    title: "Instance Shape"
    description: "The compute shape to use."
  instance_name:
    type: string
    required: false
    visible: false
    title: "Instance Name"
    description: "Name for the instance"
  availability_domain:
    type: number
    required: false
    visible: false
    title: "Availability Domain"
    description: "The availability domain to deploy the compute instances"
  userdata:
    type: string
    required: false
    visible: false
    title: "userdata directory"
    description: "Name of the userdata directory"
  cloudinit_ps1:
    type: string
    required: false
    visible: false
    title: "cloudinit_ps1 name"
    description: "Name of the cloudinit_ps1 script"
  cloudinit_config:
    type: string
    required: false
    visible: false
    title: "cloudinit_config name"
    description: "Name of the cloudinit_config file"
  index_html:
    type: string
    required: false
    visible: false
    title: "index_html file"
    description: "Name of the index_html file"
  image_os:
    type: string
    required: false
    visible: false
    title: "OS Image"
    description: "The OS image to use"
  image_os_version:
    type: string
    required: false
    visible: false
    title: "OS version"
    description: "Version of the image os"
  is_winrm_configured_for_image:
    type: boolean
    required: false
    visible: false
    title: "WinRM enabled Image ?"
    description: "WinRM support in image"
  is_winrm_configured_for_ssl:
    type: boolean
    required: false
    visible: false
    title: "Use SSL for WinRM ?"
    description: "Use SSL for WinRM"